on:
  push:
    branches:    
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    name: Build  
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false      
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm run build --prefix ${GITHUB_WORKSPACE}/src
      - run: npm run check --prefix ${GITHUB_WORKSPACE}/src

  test:
    needs: build
    name: Run Tests    
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false      
      - name: Use Node.js
        uses: actions/setup-node@v2       
      - name: Generate config
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: /src/config/env.json
          json: ${{ secrets.API_CONFIG }}      
      - name: Install dependencies
        run: npm install --prefix ${GITHUB_WORKSPACE}/src
      - name: Run Tests
        run: tags="@coins" npm run test --prefix ${GITHUB_WORKSPACE}/src        